import { environment } from "src/environments/environment";

export const elnEndpointsConfig: EndpointConfig = {
  endpoints: {
    getProducts:  `${environment.API_BASE_PATH}`+'/product/get-products',
    postProduct:  `${environment.API_BASE_PATH}`+'/product/create-product',
    updateProduct:  `${environment.API_BASE_PATH}`+'/product/update-product',
    deleteProduct:  `${environment.API_BASE_PATH}`+'/product/delete-product',
    getDosages:  `${environment.API_BASE_PATH}`+'/dosage/get-dosages',
    postDosage:  `${environment.API_BASE_PATH}`+'/dosage/save-dosage-formulations',
    updateDosage:  `${environment.API_BASE_PATH}`+'/dosage/update-dosage-formulations',
    deleteDosage:  `${environment.API_BASE_PATH}`+'/dosage/delete-dosage',
    getTests:  `${environment.API_BASE_PATH}`+'/lab-test/get-lab-tests',
    getTestByID:  `${environment.API_BASE_PATH}`+'/lab-test/get-lab-test-by-id',
    createTest:  `${environment.API_BASE_PATH}`+'/lab-test/create-tests',
    updateTest:  `${environment.API_BASE_PATH}`+'/lab-test/update-lab-test',
    deleteTest:  `${environment.API_BASE_PATH}`+'/lab-test/delete-lab-test',
    getTeams:  `${environment.API_BASE_PATH}`+'/teams/get-teams',
    createTeam:  `${environment.API_BASE_PATH}`+'/teams/create-team',
    updateTeam:  `${environment.API_BASE_PATH}`+'/teams/update-team',
    deleteTeam:  `${environment.API_BASE_PATH}`+'/teams/delete-team',
    getUsers:  `${environment.API_BASE_PATH}`+'/usersDetails/get-users-details',
    createUser:  `${environment.API_BASE_PATH}`+'/usersDetails/create-users-details',
    updateUser:  `${environment.API_BASE_PATH}`+'/usersDetails/update-users-details',
    getUserByID:  `${environment.API_BASE_PATH}`+'/usersDetails/get-users-details-by-id',
    deleteUser:  `${environment.API_BASE_PATH}`+'/usersDetails/delete-users-details',
    getExcipients: `${environment.API_BASE_PATH}`+'/excipients/get-excipients',
    createExcipient: `${environment.API_BASE_PATH}`+'/excipients/create-excipient',
    updateExcipient: `${environment.API_BASE_PATH}`+'/excipients/update-excipient',
    deleteExcipient: `${environment.API_BASE_PATH}`+'/excipients/delete-excipient',
    getDepartments: `${environment.API_BASE_PATH}`+'/department/get-departments',
    getUserRoles: `${environment.API_BASE_PATH}`+'/userrole/get-user-roles',
    createProject: `${environment.API_BASE_PATH}`+'/project/create-project',
    updateProject: `${environment.API_BASE_PATH}`+'/project/update-project',
    deleteProject: `${environment.API_BASE_PATH}`+'/project/delete-project',
    getProjects: `${environment.API_BASE_PATH}`+'/project/get-projects',
    getProjectById: `${environment.API_BASE_PATH}`+'/project/get-project-by-id',
    getProjectsTeams: `${environment.API_BASE_PATH}`+'/project/get-formulations-teams',
    getProjectsTeamsId: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-projects-by-dosage-or-team-id?teamId=10',
    createFormulationProject: `${environment.API_BASE_PATH}`+'/formulation-dashboard/create-project',
    updateFormulationProject: `${environment.API_BASE_PATH}`+'/formulation-dashboard/update-project',
    deleteFormulationProject: `${environment.API_BASE_PATH}`+'/formulation-dashboard/delete-project',
    getFormulationProjects: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-projects',
    getFormulationBatchNumber: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-batch-number',
    getFormulationProjectById: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-project-by-id',
    getFormulationProjectsTeams: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-formulations-teams',
    getFormualtionDashboardExperiments: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-experiments',
    getFormulationProjectsTeamsId:
    `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-projects-by-dosage-or-team-id?teamId=10',
    getMarkets: `${environment.API_BASE_PATH}`+'/market/get-markets',
    getExperiments: `${environment.API_BASE_PATH}`+'/experiment/get-experiments',
    createExperiment: `${environment.API_BASE_PATH}`+'/experiment/create-experiment',
    // createExperiment: 'experiment/create-experiment-attachment',
    saveExcipient: `${environment.API_BASE_PATH}`+'/experiment/save-excipient',
    saveExperimentDetails: `${environment.API_BASE_PATH}`+'/experiment/save-experiment-details',
    updateExperimentDetails: `${environment.API_BASE_PATH}`+'/experiment/update-experiment-details',
    saveExperimentAttachment: `${environment.API_BASE_PATH}`+'/experiment/save-experiment-attachment',
    getExperimentsById: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-experiments-by-user-id?userId=3',
    getExperimentById: `${environment.API_BASE_PATH}`+'/experiment/get-experiment-by-id',
    getExperimentDetailsById: `${environment.API_BASE_PATH}`+'/experiment/get-experiment-details-by-id',
    getExcipientDetailsById: `${environment.API_BASE_PATH}`+'/experiment/get-excipient-by-experimentId',
    getFormulationsExperimentById: `${environment.API_BASE_PATH}`+'/formulation-dashboard/get-experiment-by-id',
    createTestRequestForm: `${environment.API_BASE_PATH}`+'/test-request-form/create-test-request-form',
    updateTestRequestForm: `${environment.API_BASE_PATH}`+'/test-request-form/update-test-request-form',
    getTestRequestForm: `${environment.API_BASE_PATH}`+'/test-request-form/get-test-request-forms',
    getExperimentAttachmentContent: `${environment.API_BASE_PATH}`+'/experiment/get-experiment-attachment-content',
    getExperimentAttachmentById: `${environment.API_BASE_PATH}`+'/experiment/search-experiment-attachments',
    deleteExperimentAttachment: `${environment.API_BASE_PATH}`+'/experiment/delete-experiment-attachment',
    saveTrf: `${environment.API_BASE_PATH}`+'/test-request-form/create-test-request-form',
    getAnalysisList: `${environment.API_BASE_PATH}`+'/analysis/get-analysis-list',
    getAnalysisListByTeamId: `${environment.API_BASE_PATH}`+'/analysis/get-analysis-by-team-id',
    getAnalysisById: `${environment.API_BASE_PATH}`+'/analysis/get-analysis-by-id',
    getAnalysisDetailsById: `${environment.API_BASE_PATH}`+'/analysis/get-analysis-details-by-id',
    getExcipientAnalysisDetailsById: `${environment.API_BASE_PATH}`+'/analysis/get-excipient-by-analysisId',
    getTrfResultsById: `${environment.API_BASE_PATH}`+'/analysis/get-test-requests-by-analysi-id',
    getResultsDTById: `${environment.API_BASE_PATH}`+'/analysis/get-test-requests-by-analysisId',
    createAnalysisTestRequestForm: `${environment.API_BASE_PATH}`+'/analysis/create-test-request-form',
    updateAnalysisTestRequestForm: `${environment.API_BASE_PATH}`+'/analysis/update-test-request-form',
    getAnalysisTestRequestForms: `${environment.API_BASE_PATH}`+'/analysis/get-trf-by-analysisId',
    saveAnalysisDetails: `${environment.API_BASE_PATH}`+'/analysis/save-analysis-details',
    saveAnalysisExcipient: `${environment.API_BASE_PATH}`+'/analysis/save-analysis-excipient',
    searchAnalysisAttachments: `${environment.API_BASE_PATH}`+'/analysis/search-analysis-attachments',
    saveAnalysisAttachments: `${environment.API_BASE_PATH}`+'/analysis/save-analysis-attachment',
    createAnalysis: `${environment.API_BASE_PATH}`+'/analysis/create-analysis',
    updateExperimentStatus: `${environment.API_BASE_PATH}`+'/experiment/update-experiment-status',
    updateAnalysisStatus: `${environment.API_BASE_PATH}`+'/analysis/update-analysis-status',
    getExperimentsByStatus: `${environment.API_BASE_PATH}`+'/experiment/get-experiments-by-status',
    getAnalysisByStatus: `${environment.API_BASE_PATH}`+'/analysis/get-analysis-by-status',
    getUserDetailsByRoleId: `${environment.API_BASE_PATH}`+'/analysis/get-user-details-by-role-id',
    createAnalysisReview: `${environment.API_BASE_PATH}`+'/analysis/create-analysis-review',
    updateAnalysisReview: `${environment.API_BASE_PATH}`+'/analysis/udpate-analysis-review',
    getAnalysisReview: `${environment.API_BASE_PATH}`+'/analysis/get-analysis-review-by-analysis-id',
    getExperimentReviewByExperimentId: `${environment.API_BASE_PATH}`+'/experiment/get-experiment-review-by-experiment-id',
    updateExperimentReview: `${environment.API_BASE_PATH}`+'/experiment/udpate-experiment-review',
    createExperimentReview: `${environment.API_BASE_PATH}`+'/experiment/create-experiment-review',
    updateTestRequestFormResult: `${environment.API_BASE_PATH}`+'/analysis/update-test-request-form-results',
    login:`${environment.API_BASE_PATH}`+'/login/login',
    validMail:`${environment.API_BASE_PATH}`+'/login/forgot-password',
    verifyOtp:`${environment.API_BASE_PATH}`+'/login/validate-otp',
    update:`${environment.API_BASE_PATH}`+'/login/updatePassword'
  },
};

export interface EndpointConfig {
  endpoints: {
    [key: string]: any;
  };
}
